name: Generate documentation website

on:
  push:
    branches:
      - "**"
      - "!gh-pages"

permissions:
  contents: write

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y doxygen graphviz

      - name: run doxygen
        run: cd docs && doxygen

      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
          keep_files: true
          destination_dir: ${{ github.ref_name }} # groups docs by branch
