name: Linter and formatter check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-14 libwayland-dev libxkbcommon-dev xorg-dev

      - name: setup
        run: ./scripts/setup.sh

      - name: lint
        run: make lint

      - name: format
        run: make ci-format-check
