name: Linter and formatter check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  code-analysis:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: lint
        run: make lint

      - name: format
        run: make ci-format-check
