name: Tests

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        build_type: [debug, release]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: install ubuntu dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y g++-14 libwayland-dev libxkbcommon-dev xorg-dev

      - name: setup
        run: ./scripts/setup.sh

      - name: run test target
        run: make test CXX=g++-14 BUILD=${{ matrix.build_type }}
